version: "2"
services:
  go-parser:
    image: golang:1.8
    volumes:
    - .:/go/src/github.com/vavas/go-parser
    working_dir: /go/src/github.com/vavas/go-parser
    command: ./dist/go-parser
    expose:
    - 80
